/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventana;

import BusinessLogic.Inventario;
import Data.Actividad;
import Data.Usuario;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lau
 */
public class VentanaActividades extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaActividades() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEventos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCursos = new javax.swing.JList<>();
        verCursos = new javax.swing.JButton();
        verEventos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACTIVIDADES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 280, 60));

        jLabel3.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EVENTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 30));

        jLabel4.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CURSOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 80, 40));

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setFont(new java.awt.Font("Meiryo", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        listaEventos.setBackground(new java.awt.Color(0, 51, 51));
        listaEventos.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        listaEventos.setForeground(new java.awt.Color(255, 255, 255));
        listaEventos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seminario Ingenieros", "La importancia de evacuar", "Colombia", "Superaciones personales", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaEventos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 180));

        listaCursos.setBackground(new java.awt.Color(0, 51, 51));
        listaCursos.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        listaCursos.setForeground(new java.awt.Color(255, 255, 255));
        listaCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Futbol Femenino", "Rugbi Femenino", "Rugbi Masculino", "Clases de salsa" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaCursos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 230, 180));

        verCursos.setBackground(new java.awt.Color(0, 0, 51));
        verCursos.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        verCursos.setForeground(new java.awt.Color(255, 255, 255));
        verCursos.setText("VER");
        verCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosActionPerformed(evt);
            }
        });
        getContentPane().add(verCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        verEventos.setBackground(new java.awt.Color(0, 0, 51));
        verEventos.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        verEventos.setForeground(new java.awt.Color(255, 255, 255));
        verEventos.setText("VER");
        verEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEventosActionPerformed(evt);
            }
        });
        getContentPane().add(verEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/eventosicon.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/cursosicon.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 601, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaMenú ventana = new VentanaMenú(); 
         Usuario invitado = new Usuario("--", "--", "--", 0000, "--", "--", "--", new ArrayList<>(), new ArrayList<>());
          Usuario user = VentanaPrincipal.getUsuario();
          System.out.println(user);
       ventana.Verificar(user);
       ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void verCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosActionPerformed
           String curso= listaCursos.getSelectedValue();
        Inventario inventario= new Inventario();
        JFrame parentFrame = new JFrame(); 
        ArrayList<Actividad> listaActividades = new ArrayList<>(inventario.Cursos());
         for (Actividad alista : listaActividades) {
            if (alista.getNombre().equals(curso)){
                  
       JOptionPane.showMessageDialog(parentFrame, alista.toString());
            }
    }  
    }//GEN-LAST:event_verCursosActionPerformed

    private void verEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEventosActionPerformed
        String evento= listaEventos.getSelectedValue();
        Inventario inventario= new Inventario();
        JFrame parentFrame = new JFrame(); 
        ArrayList<Actividad> listaActividades = new ArrayList<>(inventario.Eventos());
         for (Actividad alista : listaActividades) {
            if (alista.getNombre().equals(evento)){
                  
       JOptionPane.showMessageDialog(parentFrame, alista.toString());
            }
    }//GEN-LAST:event_verEventosActionPerformed
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaCursos;
    private javax.swing.JList<String> listaEventos;
    private javax.swing.JButton verCursos;
    private javax.swing.JButton verEventos;
    // End of variables declaration//GEN-END:variables
}

