/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventana;

/**
 *
 * @author Lau
 */
public class VentanaEdificios extends javax.swing.JFrame {

    /**
     * Creates new form Ventana12
     */
    public VentanaEdificios() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBibliotecas = new javax.swing.JButton();
        btnMuseos = new javax.swing.JButton();
        btnAuditorios = new javax.swing.JButton();
        btnED = new javax.swing.JButton();
        btnRecreacion1 = new javax.swing.JButton();
        btnEdificiosFacultad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 700));
        setSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(153, 153, 153));
        btnVolver.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 110, 40));

        jLabel5.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDIFICIOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        btnBibliotecas.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnBibliotecas.setText("BIBLIOTECAS");
        btnBibliotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBibliotecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 210, 40));

        btnMuseos.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnMuseos.setText("MUSEOS");
        btnMuseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuseosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuseos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 40));

        btnAuditorios.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnAuditorios.setText("AUDITORIOS");
        btnAuditorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditoriosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAuditorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 210, 40));

        btnED.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnED.setText("EDIFICIOS FACULTAD");
        btnED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDActionPerformed(evt);
            }
        });
        getContentPane().add(btnED, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 210, 40));

        btnRecreacion1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        btnRecreacion1.setText("ZONAS DE RECREACION");
        btnRecreacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecreacion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecreacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 210, 40));

        btnEdificiosFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(btnEdificiosFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
 VentanaLugares ventana = new VentanaLugares();
        ventana.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBibliotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecasActionPerformed
        VentanaMapaBi ventana = new VentanaMapaBi();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBibliotecasActionPerformed

    private void btnMuseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuseosActionPerformed
          VentanaMapaMuseos ventana = new VentanaMapaMuseos();
        ventana.setVisible(true);
        this.setVisible(false);         
    }//GEN-LAST:event_btnMuseosActionPerformed

    private void btnAuditoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditoriosActionPerformed
        VentanaMapaAuditorios ventana = new VentanaMapaAuditorios();
        ventana.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_btnAuditoriosActionPerformed

    private void btnEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDActionPerformed
        VentanaMapaEd ventana = new VentanaMapaEd();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEDActionPerformed

    private void btnRecreacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecreacion1ActionPerformed
        VentanaMapaZonaRE ventana = new VentanaMapaZonaRE();
        ventana.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_btnRecreacion1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditorios;
    private javax.swing.JButton btnBibliotecas;
    private javax.swing.JButton btnED;
    private javax.swing.JLabel btnEdificiosFacultad;
    private javax.swing.JButton btnMuseos;
    private javax.swing.JButton btnRecreacion1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}

