/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventana;

import BusinessLogic.ControlBD;
import BusinessLogic.Inventario;
import Data.Edificio;
import Data.Lugar;
import static GUI.Ventana.VentanaMenú.txtrecibe;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lau
 */
public class VentanaMapaEd extends javax.swing.JFrame {
String [] botones= {"Volver","Guardar"};
 Inventario inventario= new Inventario();
       ArrayList<Lugar> listaEdificios = new ArrayList<>(inventario.CrearEF());
    /**
     * Creates new form VentanaMapaEd
     */
    public VentanaMapaEd() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCineyTv = new javax.swing.JButton();
        btnExtensionInvestigacion = new javax.swing.JButton();
        btnBiologia = new javax.swing.JButton();
        btnPosIngenieria = new javax.swing.JButton();
        btnLabElecMec = new javax.swing.JButton();
        btnZootecnia = new javax.swing.JButton();
        btnEconomia = new javax.swing.JButton();
        btnHidraulica = new javax.swing.JButton();
        btnLabsIngQuimica = new javax.swing.JButton();
        btnAulasIng = new javax.swing.JButton();
        btnCT = new javax.swing.JButton();
        btnObservatorio = new javax.swing.JButton();
        btnSINDU = new javax.swing.JButton();
        btnAgronomia = new javax.swing.JButton();
        btnDiseño = new javax.swing.JButton();
        btnSociologia = new javax.swing.JButton();
        btnDerecho = new javax.swing.JButton();
        btnPolideportivo = new javax.swing.JButton();
        btnOdontologia = new javax.swing.JButton();
        btnGenetica19 = new javax.swing.JButton();
        btnEnfermeria = new javax.swing.JButton();
        btnVeterianaria = new javax.swing.JButton();
        btnPosHumanas = new javax.swing.JButton();
        btnAulasHumanas = new javax.swing.JButton();
        btnGeociencias = new javax.swing.JButton();
        btnLenguas = new javax.swing.JButton();
        btnIngAgricola = new javax.swing.JButton();
        btnViejo = new javax.swing.JButton();
        btnQuimica = new javax.swing.JButton();
        btnFarmacia = new javax.swing.JButton();
        btnConservatorio = new javax.swing.JButton();
        btnFem = new javax.swing.JButton();
        btnFilosofia = new javax.swing.JButton();
        btnMedicina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(51, 0, 0));
        btnSalir.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 90, 40));

        btnVolver.setBackground(new java.awt.Color(0, 0, 51));
        btnVolver.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 90, 40));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDIFICIOS DE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EL EDIFICIO QUE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FACULTAD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 910, -1, -1));

        btnCineyTv.setBackground(new java.awt.Color(255, 0, 0));
        btnCineyTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCineyTvActionPerformed(evt);
            }
        });
        getContentPane().add(btnCineyTv, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 20, 10));

        btnExtensionInvestigacion.setBackground(new java.awt.Color(255, 0, 0));
        btnExtensionInvestigacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtensionInvestigacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnExtensionInvestigacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 20, 10));

        btnBiologia.setBackground(new java.awt.Color(255, 0, 0));
        btnBiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiologiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 20, 10));

        btnPosIngenieria.setBackground(new java.awt.Color(255, 0, 0));
        btnPosIngenieria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosIngenieriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPosIngenieria, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 20, 10));

        btnLabElecMec.setBackground(new java.awt.Color(255, 0, 0));
        btnLabElecMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabElecMecActionPerformed(evt);
            }
        });
        getContentPane().add(btnLabElecMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 20, 10));

        btnZootecnia.setBackground(new java.awt.Color(255, 0, 0));
        btnZootecnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZootecniaActionPerformed(evt);
            }
        });
        getContentPane().add(btnZootecnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 20, 10));

        btnEconomia.setBackground(new java.awt.Color(255, 0, 0));
        btnEconomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEconomiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEconomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 20, 10));

        btnHidraulica.setBackground(new java.awt.Color(255, 0, 0));
        btnHidraulica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHidraulicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHidraulica, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 20, 10));

        btnLabsIngQuimica.setBackground(new java.awt.Color(255, 0, 0));
        btnLabsIngQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabsIngQuimicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLabsIngQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 20, 10));

        btnAulasIng.setBackground(new java.awt.Color(255, 0, 0));
        btnAulasIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAulasIngActionPerformed(evt);
            }
        });
        getContentPane().add(btnAulasIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 20, 10));

        btnCT.setBackground(new java.awt.Color(255, 0, 0));
        btnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTActionPerformed(evt);
            }
        });
        getContentPane().add(btnCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 20, 10));

        btnObservatorio.setBackground(new java.awt.Color(255, 0, 0));
        btnObservatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnObservatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 20, 10));

        btnSINDU.setBackground(new java.awt.Color(255, 0, 0));
        btnSINDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSINDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnSINDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, 20, 10));

        btnAgronomia.setBackground(new java.awt.Color(255, 0, 0));
        btnAgronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgronomiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 20, 10));

        btnDiseño.setBackground(new java.awt.Color(255, 0, 0));
        btnDiseño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiseñoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 750, 20, 10));

        btnSociologia.setBackground(new java.awt.Color(255, 0, 0));
        btnSociologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociologiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSociologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, 20, 10));

        btnDerecho.setBackground(new java.awt.Color(255, 0, 0));
        btnDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 20, 10));

        btnPolideportivo.setBackground(new java.awt.Color(255, 0, 0));
        btnPolideportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolideportivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPolideportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 20, 10));

        btnOdontologia.setBackground(new java.awt.Color(255, 0, 0));
        btnOdontologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdontologiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnOdontologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 20, 10));

        btnGenetica19.setBackground(new java.awt.Color(255, 0, 0));
        btnGenetica19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenetica19ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenetica19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 20, 10));

        btnEnfermeria.setBackground(new java.awt.Color(255, 0, 0));
        btnEnfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfermeriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnfermeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 20, 10));

        btnVeterianaria.setBackground(new java.awt.Color(255, 0, 0));
        btnVeterianaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeterianariaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeterianaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 20, 10));

        btnPosHumanas.setBackground(new java.awt.Color(255, 0, 0));
        btnPosHumanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosHumanasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPosHumanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, 20, 10));

        btnAulasHumanas.setBackground(new java.awt.Color(255, 0, 0));
        btnAulasHumanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAulasHumanasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAulasHumanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 740, 20, 10));

        btnGeociencias.setBackground(new java.awt.Color(255, 0, 0));
        btnGeociencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeocienciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeociencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 730, 20, 10));

        btnLenguas.setBackground(new java.awt.Color(255, 0, 0));
        btnLenguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenguasActionPerformed(evt);
            }
        });
        getContentPane().add(btnLenguas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 800, 20, 10));

        btnIngAgricola.setBackground(new java.awt.Color(255, 0, 0));
        btnIngAgricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngAgricolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngAgricola, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 740, 20, 10));

        btnViejo.setBackground(new java.awt.Color(255, 0, 0));
        btnViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViejoActionPerformed(evt);
            }
        });
        getContentPane().add(btnViejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 20, 10));

        btnQuimica.setBackground(new java.awt.Color(255, 0, 0));
        btnQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuimicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 20, 10));

        btnFarmacia.setBackground(new java.awt.Color(255, 0, 0));
        btnFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 20, 10));

        btnConservatorio.setBackground(new java.awt.Color(255, 0, 0));
        btnConservatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConservatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConservatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 20, 10));

        btnFem.setBackground(new java.awt.Color(255, 0, 0));
        btnFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemActionPerformed(evt);
            }
        });
        getContentPane().add(btnFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 20, 10));

        btnFilosofia.setBackground(new java.awt.Color(255, 0, 0));
        btnFilosofia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilosofiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilosofia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 800, 20, 10));

        btnMedicina.setBackground(new java.awt.Color(255, 0, 0));
        btnMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 20, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/MAPITAxd.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 810));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DESEA VER. ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HAGA CLICK SOBRE  ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/edfacultadicon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
               VentanaEdificios ventana = new VentanaEdificios();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCineyTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCineyTvActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/cineytv.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("cine y televisión")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                    if (variable==0){
                        
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnCineyTvActionPerformed

    private void btnExtensionInvestigacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtensionInvestigacionActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/ie.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("investigacion y Extension")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                       if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
        }
    }//GEN-LAST:event_btnExtensionInvestigacionActionPerformed

    private void btnBiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiologiaActionPerformed
      for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/biologia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
      }
    }//GEN-LAST:event_btnBiologiaActionPerformed

    private void btnPosIngenieriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosIngenieriaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/posgrados ing.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("posgrados ingenieria")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
                    
               }
        }
    }//GEN-LAST:event_btnPosIngenieriaActionPerformed

    private void btnLabElecMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabElecMecActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/laoratorios ing.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("laboratorios ingenieria")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnLabElecMecActionPerformed

    private void btnZootecniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZootecniaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/zootecnia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("zootecnia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
        }
    }//GEN-LAST:event_btnZootecniaActionPerformed

    private void btnEconomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEconomiaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/economia1.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("economia sur")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
        }
    }//GEN-LAST:event_btnEconomiaActionPerformed

    private void btnHidraulicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHidraulicaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/laboratorio hidraulica.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("laboratorios de Hidraulica")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
        }
    }//GEN-LAST:event_btnHidraulicaActionPerformed

    private void btnLabsIngQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabsIngQuimicaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("ciencia y tecnologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    
    }//GEN-LAST:event_btnLabsIngQuimicaActionPerformed

    private void btnAulasIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAulasIngActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/aulas.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("aulas de ingenieria")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnAulasIngActionPerformed

    private void btnCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/cyt.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("ciencia y tecnologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
           }
        
      
    }//GEN-LAST:event_btnCTActionPerformed

    private void btnObservatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservatorioActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/observatorio.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("observatorio Astronomico")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnObservatorioActionPerformed

    private void btnSINDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSINDUActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("sindu")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnSINDUActionPerformed

    private void btnAgronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgronomiaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/agronomia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("agronomia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnAgronomiaActionPerformed

    private void btnDiseñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiseñoActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/diseño.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("diseño")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnDiseñoActionPerformed

    private void btnSociologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociologiaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/Sociologia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("sociologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnSociologiaActionPerformed

    private void btnDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechoActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/derecho.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("derecho")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnDerechoActionPerformed

    private void btnPolideportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolideportivoActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/polideportivo.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("polideportivo")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnPolideportivoActionPerformed

    private void btnGenetica19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenetica19ActionPerformed
         for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/genetica.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("genetica")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }// TODO add your handling code here:
    }//GEN-LAST:event_btnGenetica19ActionPerformed

    private void btnOdontologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdontologiaActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/ed1.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("odontologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnOdontologiaActionPerformed

    private void btnEnfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfermeriaActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/enfermeria.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("enfermeria")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnEnfermeriaActionPerformed

    private void btnVeterianariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeterianariaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/veterinaria.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("veterinaria")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnVeterianariaActionPerformed

    private void btnPosHumanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosHumanasActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/posgrados.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("posgrados humanas")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnPosHumanasActionPerformed

    private void btnAulasHumanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAulasHumanasActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/ciencias politicas.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("ciencias políticas")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnAulasHumanasActionPerformed

    private void btnGeocienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeocienciasActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("ciencia y tecnologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnGeocienciasActionPerformed

    private void btnLenguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenguasActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/lenguas.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("lenguas extranjeras")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnLenguasActionPerformed

    private void btnIngAgricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngAgricolaActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/ingagricolag"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("ing agricola")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnIngAgricolaActionPerformed

    private void btnViejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViejoActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/viejo.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("julio garavito")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnViejoActionPerformed

    private void btnQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuimicaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/quimica.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("quimica")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnQuimicaActionPerformed

    private void btnFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaciaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/farmacia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("farmacia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnFarmaciaActionPerformed

    private void btnConservatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConservatorioActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/conservatorio.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("conservatorio")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnConservatorioActionPerformed

    private void btnFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/fem.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("yu takeuchi")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnFemActionPerformed

    private void btnFilosofiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilosofiaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/filosofia.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("filosofia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnFilosofiaActionPerformed

    private void btnMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/medicina.jpg"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("medicina")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicinaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgronomia;
    private javax.swing.JButton btnAulasHumanas;
    private javax.swing.JButton btnAulasIng;
    private javax.swing.JButton btnBiologia;
    private javax.swing.JButton btnCT;
    private javax.swing.JButton btnCineyTv;
    private javax.swing.JButton btnConservatorio;
    private javax.swing.JButton btnDerecho;
    private javax.swing.JButton btnDiseño;
    private javax.swing.JButton btnEconomia;
    private javax.swing.JButton btnEnfermeria;
    private javax.swing.JButton btnExtensionInvestigacion;
    private javax.swing.JButton btnFarmacia;
    private javax.swing.JButton btnFem;
    private javax.swing.JButton btnFilosofia;
    private javax.swing.JButton btnGenetica19;
    private javax.swing.JButton btnGeociencias;
    private javax.swing.JButton btnHidraulica;
    private javax.swing.JButton btnIngAgricola;
    private javax.swing.JButton btnLabElecMec;
    private javax.swing.JButton btnLabsIngQuimica;
    private javax.swing.JButton btnLenguas;
    private javax.swing.JButton btnMedicina;
    private javax.swing.JButton btnObservatorio;
    private javax.swing.JButton btnOdontologia;
    private javax.swing.JButton btnPolideportivo;
    private javax.swing.JButton btnPosHumanas;
    private javax.swing.JButton btnPosIngenieria;
    private javax.swing.JButton btnQuimica;
    private javax.swing.JButton btnSINDU;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSociologia;
    private javax.swing.JButton btnVeterianaria;
    private javax.swing.JButton btnViejo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnZootecnia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
