/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventana;

import Data.Usuario;
import java.util.ArrayList;

public class VentanaLugares extends javax.swing.JFrame {

    /**
     * Creates new form Ventana13
     */
    public VentanaLugares() {
        initComponents();
        this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnParqueadero = new javax.swing.JButton();
        btnZonaComun = new javax.swing.JButton();
        btnEdicifios = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnZonaComidas = new javax.swing.JButton();
        btnPorterias = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LUGARES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        btnParqueadero.setBackground(new java.awt.Color(0, 51, 51));
        btnParqueadero.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnParqueadero.setForeground(new java.awt.Color(255, 255, 255));
        btnParqueadero.setText("PARQUEADEROS");
        btnParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParqueaderoActionPerformed(evt);
            }
        });
        getContentPane().add(btnParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 150, 40));

        btnZonaComun.setBackground(new java.awt.Color(0, 51, 51));
        btnZonaComun.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnZonaComun.setForeground(new java.awt.Color(255, 255, 255));
        btnZonaComun.setText("ZONA COMUN");
        btnZonaComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaComunActionPerformed(evt);
            }
        });
        getContentPane().add(btnZonaComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 150, 40));

        btnEdicifios.setBackground(new java.awt.Color(0, 51, 51));
        btnEdicifios.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnEdicifios.setForeground(new java.awt.Color(255, 255, 255));
        btnEdicifios.setText("EDIFICIOS");
        btnEdicifios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicifiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdicifios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 150, 40));

        btnVolver.setBackground(new java.awt.Color(51, 0, 0));
        btnVolver.setFont(new java.awt.Font("Meiryo", 1, 10)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 100, 30));

        btnZonaComidas.setBackground(new java.awt.Color(0, 51, 51));
        btnZonaComidas.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnZonaComidas.setForeground(new java.awt.Color(255, 255, 255));
        btnZonaComidas.setText("ZONA DE COMIDAS");
        btnZonaComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaComidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnZonaComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 170, 40));

        btnPorterias.setBackground(new java.awt.Color(0, 51, 51));
        btnPorterias.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnPorterias.setForeground(new java.awt.Color(255, 255, 255));
        btnPorterias.setText("PORTERIAS ");
        btnPorterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorteriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/zonacoicon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/edificiosicon.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/porteriasicon.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/porteriasicon.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 150, 150));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/zonacomunicon.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 170, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEdicifiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicifiosActionPerformed
         VentanaEdificios ventana = new VentanaEdificios(); 
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEdicifiosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       
        VentanaMenú ventana = new VentanaMenú(); 
       
          Usuario user = VentanaPrincipal.getUsuario();
      
       ventana.Verificar(user);
       ventana.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnZonaComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaComidasActionPerformed
        VentanaMapaZonaFOOD ventana = new VentanaMapaZonaFOOD(); 
        ventana.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_btnZonaComidasActionPerformed

    private void btnPorteriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorteriasActionPerformed
       VentanaMapaPorterias ventana = new VentanaMapaPorterias(); 
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPorteriasActionPerformed

    private void btnParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParqueaderoActionPerformed
 VentanaMapaParking ventana = new VentanaMapaParking(); 
        ventana.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnParqueaderoActionPerformed

    private void btnZonaComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaComunActionPerformed
         VentanaMapaZonaCO ventana = new VentanaMapaZonaCO(); 
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnZonaComunActionPerformed

    /**
     * @param args the command line arguments
   
*
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdicifios;
    private javax.swing.JButton btnParqueadero;
    private javax.swing.JButton btnPorterias;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnZonaComidas;
    private javax.swing.JButton btnZonaComun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
