/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventana;

import BusinessLogic.ControlBD;
import BusinessLogic.Inventario;
import Data.Edificio;
import Data.Lugar;
import static GUI.Ventana.VentanaMenú.txtrecibe;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lau
 */
public class VentanaMapaBi extends javax.swing.JFrame {
 String [] botones= {"Volver","Guardar"};
 Inventario inventario= new Inventario();
       ArrayList<Lugar> listaEdificios = new ArrayList<>(inventario.CrearEd());
    /**
     * Creates new form VentanaMapaEd
     */
    public VentanaMapaBi() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBEconomia = new javax.swing.JButton();
        btnHemeroteca = new javax.swing.JButton();
        btnBAgronomia = new javax.swing.JButton();
        btnBposgrados = new javax.swing.JButton();
        btnBCyT = new javax.swing.JButton();
        btnBibliotecaCentral = new javax.swing.JButton();
        btnFarmacia7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(51, 0, 0));
        btnSalir.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 90, 40));

        btnVolver.setBackground(new java.awt.Color(0, 0, 51));
        btnVolver.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 90, 40));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BIBLIOTECAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HAGA CLICK SOBRE  ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 910, -1, -1));

        btnBEconomia.setBackground(new java.awt.Color(0, 0, 255));
        btnBEconomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBEconomiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBEconomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 20, 10));

        btnHemeroteca.setBackground(new java.awt.Color(0, 0, 255));
        btnHemeroteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHemerotecaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHemeroteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 20, 10));

        btnBAgronomia.setBackground(new java.awt.Color(0, 0, 255));
        btnBAgronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBAgronomiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBAgronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 20, 10));

        btnBposgrados.setBackground(new java.awt.Color(0, 0, 255));
        btnBposgrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBposgradosActionPerformed(evt);
            }
        });
        getContentPane().add(btnBposgrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 700, 20, 10));

        btnBCyT.setBackground(new java.awt.Color(0, 0, 255));
        btnBCyT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBCyTActionPerformed(evt);
            }
        });
        getContentPane().add(btnBCyT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 20, 10));

        btnBibliotecaCentral.setBackground(new java.awt.Color(0, 0, 255));
        btnBibliotecaCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecaCentralActionPerformed(evt);
            }
        });
        getContentPane().add(btnBibliotecaCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 20, 10));

        btnFarmacia7.setBackground(new java.awt.Color(0, 0, 255));
        btnFarmacia7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmacia7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFarmacia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 20, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/MAPITAxd.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 810));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LA BIBLIOTECA QUE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESEA VER. ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/bibliotecaicon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
               VentanaEdificios ventana = new VentanaEdificios();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBEconomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBEconomiaActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca economia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnBEconomiaActionPerformed

    private void btnHemerotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHemerotecaActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca hemeroteca")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
       
    }//GEN-LAST:event_btnHemerotecaActionPerformed

    private void btnBAgronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBAgronomiaActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca agronomia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnBAgronomiaActionPerformed

    private void btnBposgradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBposgradosActionPerformed
     for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca posgrados")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }
    }//GEN-LAST:event_btnBposgradosActionPerformed

    private void btnBCyTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBCyTActionPerformed
       for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca ciencia y tecnologia")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }  // TODO add your handling code here:
    }//GEN-LAST:event_btnBCyTActionPerformed

    private void btnBibliotecaCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaCentralActionPerformed
         for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("biblioteca central")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                     if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       }// TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecaCentralActionPerformed

    private void btnFarmacia7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmacia7ActionPerformed
        for (Lugar lista : listaEdificios) {
           Icon icono=new ImageIcon (getClass().getResource("/GUI/Imagenes/logo.png"));
           
                JFrame parentFrame = new JFrame();
               if (lista.getNombre().equals("")){
                   
                    int variable= JOptionPane.showOptionDialog(parentFrame, lista.toString() 
                     , "Edificio", JOptionPane.YES_NO_CANCEL_OPTION,
                      JOptionPane.WARNING_MESSAGE, icono, botones, botones[0]);
                      if (variable==1){
                        ControlBD control = new ControlBD();
                        
                      try {
                          control.guardarEdificios(txtrecibe.getText(), lista);
                      } catch (ClassNotFoundException ex) {
                          Logger.getLogger(VentanaMenú.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    }else{
                        
                    }
               }
       } // TODO add your handling code here:
    }//GEN-LAST:event_btnFarmacia7ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBAgronomia;
    private javax.swing.JButton btnBCyT;
    private javax.swing.JButton btnBEconomia;
    private javax.swing.JButton btnBibliotecaCentral;
    private javax.swing.JButton btnBposgrados;
    private javax.swing.JButton btnFarmacia7;
    private javax.swing.JButton btnHemeroteca;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
